/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MyTest_CONSTANTS_H
#define MyTest_CONSTANTS_H

#include "MyTest_types.h"



class MyTestConstants {
 public:
  MyTestConstants();

};

extern const MyTestConstants g_MyTest_constants;



#endif
