// Code generated by protoc-gen-go. DO NOT EDIT.
// source: navi.proto

/*
Package navi is a generated protocol buffer package.

It is generated from these files:
	navi.proto

It has these top-level messages:
	PingRequest
	PingResponse
	ServiceNameRequest
	ServiceNameResponse
	ServiceModeRequest
	ServiceModeResponse
	SayHelloRequest
	SayHelloResponse
*/
package navi_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Pong string `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type ServiceNameRequest struct {
}

func (m *ServiceNameRequest) Reset()                    { *m = ServiceNameRequest{} }
func (m *ServiceNameRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceNameRequest) ProtoMessage()               {}
func (*ServiceNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ServiceNameResponse struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
}

func (m *ServiceNameResponse) Reset()                    { *m = ServiceNameResponse{} }
func (m *ServiceNameResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceNameResponse) ProtoMessage()               {}
func (*ServiceNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceNameResponse) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type ServiceModeRequest struct {
}

func (m *ServiceModeRequest) Reset()                    { *m = ServiceModeRequest{} }
func (m *ServiceModeRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceModeRequest) ProtoMessage()               {}
func (*ServiceModeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ServiceModeResponse struct {
	ServiceMode string `protobuf:"bytes,1,opt,name=service_mode,json=serviceMode" json:"service_mode,omitempty"`
}

func (m *ServiceModeResponse) Reset()                    { *m = ServiceModeResponse{} }
func (m *ServiceModeResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceModeResponse) ProtoMessage()               {}
func (*ServiceModeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceModeResponse) GetServiceMode() string {
	if m != nil {
		return m.ServiceMode
	}
	return ""
}

type SayHelloRequest struct {
	YourName string `protobuf:"bytes,1,opt,name=yourName" json:"yourName,omitempty"`
}

func (m *SayHelloRequest) Reset()                    { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()               {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SayHelloRequest) GetYourName() string {
	if m != nil {
		return m.YourName
	}
	return ""
}

type SayHelloResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *SayHelloResponse) Reset()                    { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string            { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()               {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SayHelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "navi.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "navi.PingResponse")
	proto.RegisterType((*ServiceNameRequest)(nil), "navi.ServiceNameRequest")
	proto.RegisterType((*ServiceNameResponse)(nil), "navi.ServiceNameResponse")
	proto.RegisterType((*ServiceModeRequest)(nil), "navi.ServiceModeRequest")
	proto.RegisterType((*ServiceModeResponse)(nil), "navi.ServiceModeResponse")
	proto.RegisterType((*SayHelloRequest)(nil), "navi.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "navi.SayHelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Navi service

type NaviClient interface {
	// rpc server必须实现的接口，返回字符串 "pong" 即可
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// rpc server必须实现的接口，返回服务名称，为首字母大写的驼峰格式，例如 "AsvService"
	ServiceName(ctx context.Context, in *ServiceNameRequest, opts ...grpc.CallOption) (*ServiceNameResponse, error)
	// rpc server必须实现的接口，说明该server是以什么模式运行，分为dev和prod；dev为开发版本，prod为生产版本
	ServiceMode(ctx context.Context, in *ServiceModeRequest, opts ...grpc.CallOption) (*ServiceModeResponse, error)
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type naviClient struct {
	cc *grpc.ClientConn
}

func NewNaviClient(cc *grpc.ClientConn) NaviClient {
	return &naviClient{cc}
}

func (c *naviClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/navi.navi/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naviClient) ServiceName(ctx context.Context, in *ServiceNameRequest, opts ...grpc.CallOption) (*ServiceNameResponse, error) {
	out := new(ServiceNameResponse)
	err := grpc.Invoke(ctx, "/navi.navi/ServiceName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naviClient) ServiceMode(ctx context.Context, in *ServiceModeRequest, opts ...grpc.CallOption) (*ServiceModeResponse, error) {
	out := new(ServiceModeResponse)
	err := grpc.Invoke(ctx, "/navi.navi/ServiceMode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *naviClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := grpc.Invoke(ctx, "/navi.navi/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Navi service

type NaviServer interface {
	// rpc server必须实现的接口，返回字符串 "pong" 即可
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// rpc server必须实现的接口，返回服务名称，为首字母大写的驼峰格式，例如 "AsvService"
	ServiceName(context.Context, *ServiceNameRequest) (*ServiceNameResponse, error)
	// rpc server必须实现的接口，说明该server是以什么模式运行，分为dev和prod；dev为开发版本，prod为生产版本
	ServiceMode(context.Context, *ServiceModeRequest) (*ServiceModeResponse, error)
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

func RegisterNaviServer(s *grpc.Server, srv NaviServer) {
	s.RegisterService(&_Navi_serviceDesc, srv)
}

func _Navi_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaviServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/navi.navi/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaviServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Navi_ServiceName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaviServer).ServiceName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/navi.navi/ServiceName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaviServer).ServiceName(ctx, req.(*ServiceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Navi_ServiceMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaviServer).ServiceMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/navi.navi/ServiceMode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaviServer).ServiceMode(ctx, req.(*ServiceModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Navi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NaviServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/navi.navi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NaviServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Navi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "navi.navi",
	HandlerType: (*NaviServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Navi_Ping_Handler,
		},
		{
			MethodName: "ServiceName",
			Handler:    _Navi_ServiceName_Handler,
		},
		{
			MethodName: "ServiceMode",
			Handler:    _Navi_ServiceMode_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _Navi_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "navi.proto",
}

func init() { proto.RegisterFile("navi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x5b, 0x14, 0x41, 0xb9, 0x14, 0x01, 0xc7, 0x87, 0x42, 0x26, 0xf0, 0xc4, 0x00, 0x45,
	0x82, 0x05, 0x89, 0x95, 0x81, 0x85, 0x0a, 0xb5, 0x3f, 0x00, 0x19, 0x7a, 0x8a, 0x22, 0x35, 0xbe,
	0x10, 0xb7, 0x95, 0xba, 0xf1, 0xd3, 0x51, 0x62, 0x9b, 0xb8, 0x4e, 0x36, 0xdf, 0x9b, 0xd7, 0x4f,
	0x72, 0x8f, 0x02, 0xa0, 0xe4, 0x26, 0x9f, 0x94, 0x15, 0xaf, 0x18, 0xa3, 0xfa, 0x2c, 0x8e, 0x20,
	0xfe, 0xc8, 0x55, 0x36, 0xa3, 0x9f, 0x35, 0xe9, 0x95, 0x10, 0x30, 0x36, 0xa3, 0x2e, 0x59, 0x69,
	0x42, 0x84, 0xa8, 0x64, 0x95, 0x25, 0xc3, 0xeb, 0xe1, 0xed, 0xe1, 0xac, 0x39, 0x8b, 0x73, 0xc0,
	0x39, 0x55, 0x9b, 0xfc, 0x9b, 0xa6, 0xb2, 0x20, 0x77, 0xf3, 0x19, 0xce, 0x76, 0x52, 0x0b, 0xb8,
	0x81, 0xb1, 0x36, 0xf1, 0xa7, 0x92, 0x05, 0x59, 0x50, 0xac, 0xdb, 0xaa, 0xc7, 0x7b, 0xe7, 0x45,
	0x0f, 0xcf, 0xa4, 0x5d, 0x5e, 0xc1, 0x8b, 0x90, 0x57, 0x57, 0xc5, 0x3d, 0x1c, 0xcf, 0xe5, 0xf6,
	0x8d, 0x96, 0x4b, 0xb6, 0x30, 0x4c, 0x61, 0xb4, 0xe5, 0x75, 0x35, 0x6d, 0xbf, 0xe0, 0x7f, 0x16,
	0x77, 0x70, 0xd2, 0xd6, 0xed, 0x5b, 0x12, 0x38, 0x28, 0x48, 0x6b, 0x99, 0xb9, 0xba, 0x1b, 0x1f,
	0x7f, 0xf7, 0xa0, 0x11, 0x87, 0x0f, 0x10, 0xd5, 0xa6, 0xf0, 0x74, 0xd2, 0x38, 0xf5, 0x24, 0xa6,
	0xe8, 0x47, 0x86, 0x28, 0x06, 0xf8, 0x0a, 0xb1, 0x27, 0x08, 0x13, 0x53, 0xea, 0x9a, 0x4c, 0xaf,
	0x7a, 0x9e, 0xf4, 0x50, 0xea, 0x5d, 0x03, 0x8a, 0xe7, 0x2f, 0xa0, 0xf8, 0x0e, 0xc5, 0x00, 0x5f,
	0x60, 0xe4, 0x76, 0xc6, 0x0b, 0x5b, 0xdc, 0x55, 0x96, 0x5e, 0x86, 0xb1, 0xbb, 0xfc, 0xb5, 0xdf,
	0xfc, 0x3f, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xfb, 0x5a, 0xc7, 0x4d, 0x02, 0x00,
	0x00,
}
