version: '2'
services:
  web1:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: localhost:5000/mytest_http:alpha
    env_file: ../env.ini
    ports:
      - "8081:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  web2:
    image: localhost:5000/mytest_http:alpha
    env_file: ../env.ini
    ports:
      - "8082:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  web3:
    image: localhost:5000/mytest_http:alpha
    env_file: ../env.ini
    ports:
      - "8083:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"