version: '2'
services:
  web1:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: mytest_http:alpha
    #env_file: ../env.ini
    environment:
      ZK_HOSTS: 192.168.1.17:2181;192.168.1.17:2182;192.168.1.17:2183
      SERVER_HOSTS: 192.168.1.16:8081
      KAFKA_HOSTS: 192.168.1.16:9092
      JAEGER_ADDR: 192.168.1.16:6831
      LOG_FILE: \/navi\/logs\/navi_web1.log
    ports:
      - "8081:8081"
    volumes:
      - $GOPATH/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
#    depends_on:
#      - zookeeper
  web2:
    image: mytest_http:alpha
    environment:
      ZK_HOSTS: 192.168.1.17:2181;192.168.1.17:2182;192.168.1.17:2183
      SERVER_HOSTS: 192.168.1.16:8082
      KAFKA_HOSTS: 192.168.1.16:9092
      JAEGER_ADDR: 192.168.1.16:6831
      LOG_FILE: \/navi\/logs\/navi_web2.log
    ports:
      - "8082:8081"
    volumes:
      - $GOPATH/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
#    depends_on:
#      - zookeeper
  web3:
    image: mytest_http:alpha
    environment:
      ZK_HOSTS: 192.168.1.17:2181;192.168.1.17:2182;192.168.1.17:2183
      SERVER_HOSTS: 192.168.1.16:8083
      KAFKA_HOSTS: 192.168.1.16:9092
      JAEGER_ADDR: 192.168.1.16:6831
      LOG_FILE: \/navi\/logs\/navi_web3.log
    ports:
      - "8083:8081"
    volumes:
      - $GOPATH/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
#    depends_on:
#      - zookeeper
#  zookeeper:
#    image: zookeeper
#    ports:
#      - "2181:2181"