version: '2'
services:
  web1:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: localhost:5000/mytest_http:alpha
    #env_file: ../env.ini
    environment:
      ZK_HOSTS: 192.168.1.16:2181
      SERVER_HOSTS: 192.168.1.16:9292
      KAFKA_HOSTS: 192.168.1.16:9092
    ports:
      - "8081:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  web2:
    image: localhost:5000/mytest_http:alpha
    environment:
      ZK_HOSTS: 192.168.1.16:2181
      SERVER_HOSTS: 192.168.1.16:9293
      KAFKA_HOSTS: 192.168.1.16:9092
    ports:
      - "8082:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  web3:
    image: localhost:5000/mytest_http:alpha
    environment:
      ZK_HOSTS: 192.168.1.16:2181
      SERVER_HOSTS: 192.168.1.16:9294
      KAFKA_HOSTS: 192.168.1.16:9092
    ports:
      - "8083:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"