version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ../env.ini
    ports:
      - "8081:8081"
    volumes:
      - /opt/golang/src/kuaishangtong/navi/scripts/httpservice/navi:/navi
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"